application: minipcs-176303
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: core/static/favicon.ico
  upload: core/static/favicon\.ico

- url: /static(.*)
  static_files: core/static\1
  upload: core/static.*

- url: /inscricao.*
  script: subscriptions.handlers.app

- url: .*
  script: core.main.app

