application: minipcs-176303
version: 1
runtime: python27
api_version: 2
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: .*
  script: core.main.app

